/**
 * Canonical TapCast channel catalog.
 * TikTok remains first-class; others expand the omnichannel registry around it.
 */

import type { TapCastChannelDefinition } from "./types";

const LIVE = "verified_credentials_required" as const;

export const TAPCAST_CHANNELS: TapCastChannelDefinition[] = [
  // ─── Publishing / Social ───────────────────────────────────────────────────
  {
    id: "tiktok",
    name: "TikTok",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: true,
    href: "/dashboard/experiences/tapcast/tiktok",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
    optionalEnvVars: ["TIKTOK_REDIRECT_URI", "TIKTOK_ACCESS_TOKEN"],
    documentation: "Experiences → TapCast → TikTok (first-class)",
    notes:
      "First-class TapCast. Mock draft/post/funnel OK. Live Direct Post gated on TIKTOK_ACCESS_TOKEN.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "draft_upload", "provider_draft"],
      mockPublishPath: "draft_upload",
      livePublishPath: "direct",
      media: ["short_video", "video", "carousel", "image"],
      dimensions: [
        {
          aspectRatio: "9:16",
          width: 1080,
          height: 1920,
          maxDurationSec: 600,
          maxCaptionChars: 2200,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "youtube",
    name: "YouTube Shorts",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#youtube",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["YOUTUBE_CLIENT_ID", "YOUTUBE_CLIENT_SECRET"],
    optionalEnvVars: ["YOUTUBE_REFRESH_TOKEN"],
    documentation: "YouTube Data API v3 — Shorts upload",
    notes: "Mock: prepared package + draft upload. Live upload = credentials required.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "draft_upload", "prepared_package"],
      mockPublishPath: "draft_upload",
      livePublishPath: "direct",
      media: ["short_video", "video"],
      dimensions: [
        {
          aspectRatio: "9:16",
          width: 1080,
          height: 1920,
          maxDurationSec: 60,
          maxCaptionChars: 100,
          notes: "Shorts title ≤100 chars; description separate",
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "instagram",
    name: "Instagram Reels",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#instagram",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: [
      "META_APP_ID",
      "META_APP_SECRET",
      "INSTAGRAM_BUSINESS_ACCOUNT_ID",
    ],
    optionalEnvVars: ["META_ACCESS_TOKEN"],
    documentation: "Meta Graph API — Reels / feed / stories",
    notes: "Mock: container draft + scheduled. Live publish needs Meta token.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "provider_draft", "prepared_package"],
      mockPublishPath: "provider_draft",
      livePublishPath: "direct",
      media: ["short_video", "image", "carousel", "story"],
      dimensions: [
        {
          aspectRatio: "9:16",
          width: 1080,
          height: 1920,
          maxDurationSec: 90,
          maxCaptionChars: 2200,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: true,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "facebook",
    name: "Facebook Pages",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#facebook",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["META_APP_ID", "META_APP_SECRET", "FACEBOOK_PAGE_ID"],
    optionalEnvVars: ["META_ACCESS_TOKEN"],
    documentation: "Meta Graph API — Page posts / Reels",
    notes: "Mock: scheduled Page post package. No claim of Stories API without Page token.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["video", "image", "carousel", "text", "link"],
      dimensions: [
        {
          aspectRatio: "1:1",
          width: 1080,
          height: 1080,
          maxCaptionChars: 63206,
        },
        {
          aspectRatio: "9:16",
          width: 1080,
          height: 1920,
          maxDurationSec: 90,
          notes: "Reels on Page",
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: true,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "x",
    name: "X (Twitter)",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#x",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["X_API_KEY", "X_API_SECRET"],
    optionalEnvVars: ["X_ACCESS_TOKEN", "X_ACCESS_TOKEN_SECRET"],
    documentation: "X API v2 — posts / media",
    notes: "Mock: open composer package (280 chars). Live tweet = credentials required.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "video", "link"],
      dimensions: [
        {
          aspectRatio: "16:9",
          width: 1280,
          height: 720,
          maxCaptionChars: 280,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#linkedin",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET"],
    optionalEnvVars: ["LINKEDIN_ACCESS_TOKEN"],
    documentation: "LinkedIn Marketing / Share API",
    notes: "Mock: prepared UGC package. Live share = credentials required.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "video", "link"],
      dimensions: [
        {
          aspectRatio: "1.91:1",
          width: 1200,
          height: 627,
          maxCaptionChars: 3000,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "pinterest",
    name: "Pinterest",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#pinterest",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["PINTEREST_APP_ID", "PINTEREST_APP_SECRET"],
    optionalEnvVars: ["PINTEREST_ACCESS_TOKEN"],
    documentation: "Pinterest API v5 — Pins",
    notes: "Mock: prepared Pin package. Live create Pin = credentials required.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["image", "video", "carousel", "link"],
      dimensions: [
        {
          aspectRatio: "2:3",
          width: 1000,
          height: 1500,
          maxCaptionChars: 500,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "snapchat",
    name: "Snapchat",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#snapchat",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["SNAPCHAT_CLIENT_ID", "SNAPCHAT_CLIENT_SECRET"],
    optionalEnvVars: ["SNAPCHAT_ACCESS_TOKEN"],
    documentation: "Snapchat Marketing / Creative API",
    notes:
      "Mock: prepared package + open composer only — no claim of organic public post API.",
    capabilities: {
      publishPaths: ["prepared_package", "open_composer", "manual_checklist"],
      mockPublishPath: "prepared_package",
      livePublishPath: null,
      media: ["short_video", "image", "story"],
      dimensions: [
        {
          aspectRatio: "9:16",
          width: 1080,
          height: 1920,
          maxDurationSec: 60,
          maxCaptionChars: 80,
        },
      ],
      scheduling: false,
      approvals: true,
      analytics: false,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "bluesky",
    name: "Bluesky",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#bluesky",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["BLUESKY_HANDLE", "BLUESKY_APP_PASSWORD"],
    optionalEnvVars: [],
    documentation: "AT Protocol — createRecord",
    notes: "Mock: prepared skeet package. Live post = app password required.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link"],
      dimensions: [
        {
          aspectRatio: "1:1",
          width: 1080,
          height: 1080,
          maxCaptionChars: 300,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: false,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "threads",
    name: "Threads",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#threads",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["META_APP_ID", "META_APP_SECRET", "THREADS_USER_ID"],
    optionalEnvVars: ["META_ACCESS_TOKEN"],
    documentation: "Threads API (Meta)",
    notes: "Mock: prepared text/image package. Live = Meta Threads credentials.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "carousel", "short_video"],
      dimensions: [
        {
          aspectRatio: "1:1",
          width: 1080,
          height: 1080,
          maxCaptionChars: 500,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "google_business",
    name: "Google Business Profile",
    category: "publishing_social",
    categoryLabel: "Publishing · Social",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#google_business",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: [
      "GOOGLE_BUSINESS_PROFILE_ACCOUNT_ID",
      "GOOGLE_CLIENT_ID",
      "GOOGLE_CLIENT_SECRET",
    ],
    optionalEnvVars: ["GOOGLE_REFRESH_TOKEN"],
    documentation: "Google Business Profile API — local posts",
    notes: "Mock: prepared local post. Live = GBP credentials required.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "manual_checklist"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link"],
      dimensions: [
        {
          aspectRatio: "4:3",
          width: 1200,
          height: 900,
          maxCaptionChars: 1500,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },

  // ─── Conversation / Relationship ───────────────────────────────────────────
  {
    id: "messenger",
    name: "Messenger",
    category: "conversation_relationship",
    categoryLabel: "Conversation · Relationship",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#messenger",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["META_APP_ID", "META_APP_SECRET", "MESSENGER_PAGE_ID"],
    optionalEnvVars: ["META_ACCESS_TOKEN", "META_WEBHOOK_VERIFY_TOKEN"],
    documentation: "Meta Messenger Platform",
    notes:
      "Conversation channel — not a broadcast feed. Mock: prepared message + open composer. Live send = Meta credentials (direct path declared). No organic Page post claim.",
    capabilities: {
      publishPaths: ["direct", "prepared_package", "open_composer", "manual_checklist"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link"],
      dimensions: [
        {
          aspectRatio: "1:1",
          width: 1080,
          height: 1080,
          maxCaptionChars: 2000,
        },
      ],
      scheduling: false,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: true,
      messaging: true,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    category: "conversation_relationship",
    categoryLabel: "Conversation · Relationship",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#whatsapp",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: [
      "WHATSAPP_PHONE_NUMBER_ID",
      "WHATSAPP_ACCESS_TOKEN",
      "META_APP_ID",
    ],
    optionalEnvVars: ["WHATSAPP_BUSINESS_ACCOUNT_ID"],
    documentation: "WhatsApp Cloud API — templates + session messages",
    notes:
      "Template-gated for outbound. Mock: prepared template package. Live = Cloud API credentials.",
    capabilities: {
      publishPaths: ["direct", "prepared_package", "manual_checklist"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link", "audio"],
      dimensions: [
        {
          aspectRatio: "1:1",
          width: 800,
          height: 800,
          maxCaptionChars: 1024,
          notes: "Template body limits apply",
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: true,
      messaging: true,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "instagram_dm",
    name: "Instagram DM",
    category: "conversation_relationship",
    categoryLabel: "Conversation · Relationship",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#instagram_dm",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: [
      "META_APP_ID",
      "META_APP_SECRET",
      "INSTAGRAM_BUSINESS_ACCOUNT_ID",
    ],
    optionalEnvVars: ["META_ACCESS_TOKEN"],
    documentation: "Instagram Messaging API",
    notes: "DM only — not Reels publish. Mock: prepared DM package. Live send = Meta credentials (direct path declared).",
    capabilities: {
      publishPaths: ["direct", "prepared_package", "open_composer", "manual_checklist"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link"],
      dimensions: [
        {
          aspectRatio: "1:1",
          width: 1080,
          height: 1080,
          maxCaptionChars: 1000,
        },
      ],
      scheduling: false,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: true,
      messaging: true,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "sms",
    name: "SMS",
    category: "conversation_relationship",
    categoryLabel: "Conversation · Relationship",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#sms",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_FROM_NUMBER"],
    optionalEnvVars: [],
    documentation: "Twilio SMS",
    notes: "Mock: prepared SMS checklist. Live send = Twilio credentials.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "manual_checklist"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "link"],
      dimensions: [
        {
          aspectRatio: "n/a",
          width: 0,
          height: 0,
          maxCaptionChars: 160,
          notes: "GSM-7 segment; longer = multi-segment",
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: false,
      webhooks: true,
      messaging: true,
      communityOps: false,
      requiresNativeAdaptation: true,
    },
  },

  // ─── Community / Ops ───────────────────────────────────────────────────────
  {
    id: "discord",
    name: "Discord",
    category: "community_ops",
    categoryLabel: "Community · Ops",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#discord",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["DISCORD_BOT_TOKEN", "DISCORD_GUILD_ID"],
    optionalEnvVars: ["DISCORD_WEBHOOK_URL"],
    documentation: "Discord Bot / Webhook — channel announcements",
    notes: "Community announce path. Mock: prepared message package.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link"],
      dimensions: [
        {
          aspectRatio: "16:9",
          width: 1280,
          height: 720,
          maxCaptionChars: 2000,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: false,
      attribution: true,
      oauth: true,
      webhooks: true,
      messaging: true,
      communityOps: true,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "slack_community",
    name: "Slack (Community)",
    category: "community_ops",
    categoryLabel: "Community · Ops",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#slack_community",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["SLACK_BOT_TOKEN", "SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"],
    optionalEnvVars: ["SLACK_SIGNING_SECRET"],
    documentation: "Slack Web API — channel posts (community ops, not productivity work items)",
    notes:
      "Distinct from Productivity Slack connector. Mock: prepared channel post. Live = bot token.",
    capabilities: {
      publishPaths: ["direct", "scheduled", "prepared_package", "open_composer"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link"],
      dimensions: [
        {
          aspectRatio: "16:9",
          width: 1280,
          height: 720,
          maxCaptionChars: 3000,
        },
      ],
      scheduling: true,
      approvals: true,
      analytics: false,
      attribution: true,
      oauth: true,
      webhooks: true,
      messaging: true,
      communityOps: true,
      requiresNativeAdaptation: true,
    },
  },
  {
    id: "reddit",
    name: "Reddit",
    category: "community_ops",
    categoryLabel: "Community · Ops",
    firstClass: false,
    href: "/dashboard/experiences/tapcast#reddit",
    supportsMock: true,
    liveClassification: LIVE,
    requiredEnvVars: ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET"],
    optionalEnvVars: ["REDDIT_REFRESH_TOKEN"],
    documentation: "Reddit API — subreddit submit",
    notes:
      "Mock: prepared package + manual checklist (subreddit rules). Live submit = credentials.",
    capabilities: {
      publishPaths: ["direct", "prepared_package", "open_composer", "manual_checklist"],
      mockPublishPath: "prepared_package",
      livePublishPath: "direct",
      media: ["text", "image", "link", "video"],
      dimensions: [
        {
          aspectRatio: "16:9",
          width: 1280,
          height: 720,
          maxCaptionChars: 40000,
          notes: "Title ≤300; body/selftext separate",
        },
      ],
      scheduling: false,
      approvals: true,
      analytics: true,
      attribution: true,
      oauth: true,
      webhooks: false,
      messaging: false,
      communityOps: true,
      requiresNativeAdaptation: true,
    },
  },
];

export function getTapCastChannel(id: string): TapCastChannelDefinition | undefined {
  return TAPCAST_CHANNELS.find((c) => c.id === id);
}

export function listTapCastChannels(
  category?: TapCastChannelDefinition["category"]
): TapCastChannelDefinition[] {
  if (!category) return [...TAPCAST_CHANNELS];
  return TAPCAST_CHANNELS.filter((c) => c.category === category);
}

export function listFirstClassChannels(): TapCastChannelDefinition[] {
  return TAPCAST_CHANNELS.filter((c) => c.firstClass);
}
