"use client";

import { Layers3, X } from "lucide-react";
import type { CardEditorLiveModel } from "@/components/fusion/card/card-editor-live";
import { MediaPicker } from "@/components/media/media-picker";
import type { BrandPreviewContext } from "@/lib/fusion/creative-studio/reconstitution/standard-button-catalog";
import { compositionBackgroundFromMaterialRecipe, getMaterialRecipe, materialPreviewCss } from "@/lib/fusion/creative-studio/material-engine";
import { readCardEdgeMode, setCardEdgeMode, STUDIO_EDGE_MODES, type StudioEdgeMode } from "@/lib/fusion/creative-studio/platform/edge-layout";
import { isCardSurfaceLayered, setCardSurfaceCompositionMode } from "@/lib/fusion/creative-studio/platform/layered-region";
import { readCardSurfaceDensity, setCardSurfaceDensity, type StudioCompositionDensityMode } from "@/lib/fusion/creative-studio/platform/composition-density";
import { StudioColorControl } from "./studio-color-control";

type ImageBackground = NonNullable<NonNullable<CardEditorLiveModel["config"]["rootComposition"]>["background"]>["image"];

function Range({ label, value, min, max, step = 1, suffix = "%", onChange }: { label: string; value: number; min: number; max: number; step?: number; suffix?: string; onChange: (value: number) => void }) {
  return <label className="mt-3 block text-[9px] text-white/55"><span className="flex items-center justify-between"><span>{label}</span><span className="tabular-nums text-white/35">{value}{suffix}</span></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.currentTarget.value))} className="mt-1.5 w-full accent-[#b8ff2c]" /></label>;
}

export function StudioCardSurfaceInspector({ model, brand, onClose }: { model: CardEditorLiveModel; brand: BrandPreviewContext; onClose: () => void }) {
  const root = model.config.rootComposition;
  if (!root) return null;
  const authored = root.background?.kind === "solid" && /^#[0-9a-f]{6}$/i.test(String(root.background.value || "")) ? String(root.background.value) : null;
  const brandColor = brand.backgroundColor || model.config.surfaceColor || "#0b0f19";
  const value = authored || brandColor;
  const source = root.background?.source || (authored ? "local" : "brand");
  const backgroundImage = root.background?.kind === "image" ? root.background.image : undefined;
  const leather = getMaterialRecipe("worn_saddle_leather")!;
  const density = readCardSurfaceDensity(root);
  const patchRoot = (nextRoot: typeof root, label: string, batch = false) => model.patchConfig({ rootComposition: nextRoot }, label, batch);
  const patchImage = (patch: Partial<ImageBackground>, label: string) => {
    if (!backgroundImage || root.background?.kind !== "image") return;
    patchRoot({ ...root, background: { ...root.background, image: { ...backgroundImage, ...patch } } }, label, true);
  };
  const patchImageBackground = (patch: Partial<NonNullable<typeof root.background>>, label: string) => {
    if (root.background?.kind !== "image") return;
    patchRoot({ ...root, background: { ...root.background, ...patch } }, label, true);
  };
  const applyColor = (color: string, nextSource: "brand" | "local", label: string) => patchRoot({ ...root, background: { kind: "solid", value: color, opacity: 1, source: nextSource } }, label);
  const applyImage = (asset: { url: string; mediaAssetId?: string; id: string; label?: string } | null) => patchRoot({ ...root, background: asset ? { kind: "image", source: "local", opacity: 1, saturation: 1, brightness: 1, contrast: 1, image: { src: asset.url, mediaAssetId: asset.mediaAssetId || asset.id, fit: "cover", focalX: .5, focalY: .5, scale: 1, repeat: "no-repeat", blur: 0, brightness: 1, contrast: 1, overlayColor: "#000000", overlayOpacity: .22, decorative: true, alt: asset.label || "" } } : { kind: "solid", value: brandColor, source: "brand", opacity: 1 } }, asset ? "Selected Card Surface image" : "Removed Card Surface image");
  const applyEdge = (mode: StudioEdgeMode) => patchRoot(setCardEdgeMode(root, mode), `Changed Card Surface edge to ${mode.replace("_", " ")}`);
  const applyLeather = () => patchRoot({ ...setCardEdgeMode(root, "full_bleed"), background: compositionBackgroundFromMaterialRecipe(leather) }, "Applied Worn Saddle Leather Card Surface");
  return <aside className="absolute inset-x-0 bottom-0 z-[2100] flex max-h-[62dvh] flex-col rounded-t-3xl border-t border-white/8 bg-[#0b111b]/98 text-white shadow-[0_-18px_50px_rgba(0,0,0,.36)] backdrop-blur-xl md:inset-y-0 md:left-auto md:right-0 md:max-h-none md:w-[min(360px,calc(100vw-12px))] md:rounded-none md:border-l md:border-t-0" data-testid="studio-card-surface-inspector">
    <header className="flex min-h-14 items-center gap-2 border-b border-white/8 px-4"><div className="min-w-0 flex-1"><p className="text-xs text-white/45">Card › Card Surface</p><h2 className="mt-0.5 text-sm font-semibold">Refine Card Surface</h2></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full hover:bg-white/8" aria-label="Close Inspector"><X className="h-4 w-4" /></button></header>
    <div className="min-h-0 flex-1 overflow-y-auto p-4">
      <section className="rounded-2xl border border-[#b8ff2c]/14 bg-[#b8ff2c]/[.035] p-3" data-testid="studio-card-edge-controls"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#d8ff82]/75">Visual bleed</p><p className="mt-1 text-[9px] leading-4 text-white/48">The Surface can reach device glass while content keeps its own safe area.</p><div className="mt-3 grid grid-cols-3 gap-1">{STUDIO_EDGE_MODES.map((option) => <button key={option.id} type="button" aria-pressed={readCardEdgeMode(root) === option.id} onClick={() => applyEdge(option.id)} className="min-h-12 rounded-xl bg-white/5 px-1 text-[9px] aria-pressed:bg-[#b8ff2c] aria-pressed:text-[#07100a]">{option.label}</button>)}</div></section>
      <section className="mt-5" data-card-surface-authority="root-composition"><div className="flex items-center gap-3 rounded-2xl bg-white/4 p-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-white/10" style={{ background: backgroundImage ? `linear-gradient(#0005,#0005),url(${backgroundImage.src}) center/cover` : value }}><Layers3 className="h-4 w-4 drop-shadow" /></span><div><p className="text-xs font-semibold">{backgroundImage ? "Image surface" : "Solid base"}</p><p className="text-[9px] text-white/40">{source === "brand" ? "From Brand" : "Custom on this Card"}</p></div></div>
        <p className="mt-4 text-[10px] font-semibold uppercase tracking-[.14em] text-[#a9e7ff]/70">Surface materials</p><button type="button" aria-pressed={root.background?.materialPreset === leather.id} onClick={applyLeather} className="mt-2 w-full overflow-hidden rounded-xl border border-white/10 bg-white/4 text-left aria-pressed:border-[#b8ff2c] aria-pressed:bg-[#b8ff2c]/10"><span className="block h-16 bg-cover bg-center" style={{ background: materialPreviewCss(leather) }} /><span className="block px-3 py-2 text-[10px] font-semibold">Worn Saddle Leather</span></button>
        <div className="mt-4"><MediaPicker label="Card Surface image" chooseLabel="Choose image" replaceLabel="Replace image" removeLabel="Remove" value={backgroundImage?.src || ""} valueAssetId={backgroundImage?.mediaAssetId} mediaUploadReady={model.mediaUploadReady} stockReady={model.stockReady} onAssetChange={applyImage} /></div>
        <div className="mt-4" data-testid="studio-card-surface-color"><StudioColorControl label="Base color" value={value} source={source === "brand" ? "brand" : "custom"} brandColors={[brand.primaryColor, brand.secondaryColor, brand.accentColor, brand.backgroundColor].filter((candidate): candidate is string => Boolean(candidate))} resetValue={brandColor} resetLabel="Reset to Brand background" onChange={(color, nextSource) => applyColor(color, nextSource === "brand" || nextSource === "default" ? "brand" : "local", nextSource === "default" ? "Reset Card Surface to Brand" : "Changed Card Surface base color")} /></div>
      </section>
      {backgroundImage ? <section className="mt-6 rounded-2xl border border-[#8bdcff]/12 bg-[#101824]/70 p-3" data-testid="studio-card-image-controls"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#a9e7ff]/70">Image presentation</p><div className="mt-3 grid grid-cols-4 gap-1">{(["cover","contain","fill","original"] as const).map((fit) => <button key={fit} type="button" aria-pressed={backgroundImage.fit === fit} onClick={() => patchImage({ fit }, `Changed Card Surface image fit to ${fit}`)} className="min-h-9 rounded-lg bg-white/5 text-[8px] capitalize aria-pressed:bg-[#b8ff2c] aria-pressed:text-[#07100a]">{fit}</button>)}</div><Range label="Zoom / scale" value={Math.round(backgroundImage.scale * 100)} min={50} max={250} onChange={(next) => patchImage({ scale: next / 100 }, "Changed Card Surface image scale")} /><Range label="Focal X" value={Math.round(backgroundImage.focalX * 100)} min={0} max={100} onChange={(next) => patchImage({ focalX: next / 100 }, "Changed Card Surface focal X")} /><Range label="Focal Y" value={Math.round(backgroundImage.focalY * 100)} min={0} max={100} onChange={(next) => patchImage({ focalY: next / 100 }, "Changed Card Surface focal Y")} /><p className="mt-5 text-[9px] font-semibold uppercase tracking-[.14em] text-white/42">Non-destructive treatment</p><Range label="Brightness" value={Math.round(backgroundImage.brightness * 100)} min={25} max={200} onChange={(next) => patchImage({ brightness: next / 100 }, "Changed Card Surface brightness")} /><Range label="Contrast" value={Math.round(backgroundImage.contrast * 100)} min={25} max={200} onChange={(next) => patchImage({ contrast: next / 100 }, "Changed Card Surface contrast")} /><Range label="Saturation" value={Math.round((root.background?.saturation ?? 1) * 100)} min={0} max={200} onChange={(next) => patchImageBackground({ saturation: next / 100 }, "Changed Card Surface saturation")} /><label className="mt-3 block text-[9px] text-white/55">Warmth / tint veil<input type="color" value={backgroundImage.overlayColor || "#000000"} onChange={(event) => patchImage({ overlayColor: event.currentTarget.value }, "Changed Card Surface tint")} className="mt-1.5 h-9 w-full rounded-lg border-0 bg-transparent" /></label><Range label="Overlay / veil" value={Math.round((backgroundImage.overlayOpacity || 0) * 100)} min={0} max={90} onChange={(next) => patchImage({ overlayOpacity: next / 100 }, "Changed Card Surface veil")} /><Range label="Image opacity" value={Math.round((root.background?.opacity ?? 1) * 100)} min={10} max={100} onChange={(next) => patchImageBackground({ opacity: next / 100 }, "Changed Card Surface image opacity")} /></section> : null}
      <section className="mt-6 border-t border-white/8 pt-4" data-testid="studio-card-composition-mode"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#a9e7ff]/70">Composition</p><p className="mt-1 text-[9px] leading-4 text-white/48">Flow is the default. Layered enables bounded overlap directly on Card Surface.</p><div className="mt-3 grid grid-cols-2 gap-1">{(["flow","layered"] as const).map((mode) => <button key={mode} type="button" aria-pressed={(isCardSurfaceLayered(root) ? "layered" : "flow") === mode} onClick={() => patchRoot(setCardSurfaceCompositionMode(root, mode), `Changed Card Surface composition to ${mode}`)} className="min-h-10 rounded-xl bg-white/5 text-[10px] capitalize aria-pressed:bg-[#b8ff2c] aria-pressed:text-[#07100a]">{mode}</button>)}</div><p className="mt-4 text-[9px] font-semibold uppercase tracking-[.12em] text-white/42">Density</p><div className="mt-2 grid grid-cols-4 gap-1" data-testid="studio-card-density">{(["dense","standard","airy","custom"] as StudioCompositionDensityMode[]).map((mode) => <button key={mode} type="button" aria-pressed={density.mode === mode} onClick={() => patchRoot(setCardSurfaceDensity(root, mode), `Changed Card Surface density to ${mode}`)} className="min-h-9 rounded-lg bg-white/5 px-1 text-[8px] capitalize aria-pressed:bg-[#b8ff2c] aria-pressed:text-[#07100a]">{mode}</button>)}</div>{density.mode === "custom" ? <><Range label={isCardSurfaceLayered(root) ? "Snap rhythm / row gap" : "Row gap"} value={density.rowGapPx} min={0} max={64} suffix="px" onChange={(value) => patchRoot(setCardSurfaceDensity(root, "custom", value, { rowGapPx: value }), "Changed Card Surface row gap")} /><Range label="Column gap" value={density.columnGapPx} min={0} max={64} suffix="px" onChange={(value) => patchRoot(setCardSurfaceDensity(root, "custom", density.gapPx, { columnGapPx: value }), "Changed Card Surface column gap")} /><Range label="Internal group gap" value={density.internalGroupGapPx} min={0} max={64} suffix="px" onChange={(value) => patchRoot(setCardSurfaceDensity(root, "custom", density.gapPx, { internalGroupGapPx: value }), "Changed Card Surface internal group gap")} /></> : <p className="mt-2 text-[9px] text-white/35">{isCardSurfaceLayered(root) ? `${Math.round(density.snapGrid * 100)}% placement rhythm` : `${density.rowGapPx}px row gap · ${density.columnGapPx}px column gap`}</p>}{isCardSurfaceLayered(root) ? <label className="mt-3 block text-[9px] text-white/55">Layered region height<input type="number" min={240} max={1600} step={10} value={root.compositionMode?.layeredHeightPx ?? 620} onChange={(event) => patchRoot({ ...root, compositionMode: { ...root.compositionMode!, version: 1, mode: "layered", layeredHeightPx: Math.max(240, Math.min(1600, Number(event.target.value))) } }, "Changed Card layered region height")} className="mt-1.5 h-10 w-full rounded-lg bg-white/5 px-3" /></label> : null}</section>
    </div>
  </aside>;
}
